-- Explicit base46 slot mapping shared by all five houses.
-- Slots not listed here (white, grey, pink, teal, ...) fall back to
-- peacock's closest-ΔE match against the raw palette.
return {
	base00 = "bg",
	base01 = "surface",
	base02 = "overlay",
	base03 = "muted",
	base04 = "fg_dim",
	base05 = "fg",
	base06 = "fg",
	base07 = "fg",
	base08 = "err",
	base09 = "num",
	base0a = "kw",
	base0b = "str",
	base0c = "special",
	base0d = "fn",
	base0e = "ty",
	base0f = "err",
	red = "err",
	orange = "kw",
	yellow = "num",
	green = "str",
	blue = "fn",
	purple = "ty",
	dark_purple = "ty",
	statusline_bg = "bg_dim",
	lightbg = "surface",
	line = "surface",
	darker_black = "bg_dim",
	black = "bg",
	black2 = "surface",
	one_bg = "surface",
	one_bg2 = "overlay",
	one_bg3 = "overlay",
	folder_bg = "fn",
	pmenu_bg = "ty",
}
