# dune-harkonnen - the black sun (hard monochrome)
[cursor]
color=111113 EEEDEA

[colors]
background=111113
foreground=EEEDEA
selection-background=29292E
selection-foreground=EEEDEA
urls=E4F1FF
regular0=1B1B1E
regular1=D05837
regular2=7E8D80
regular3=C4AE62
regular4=7E99B4
regular5=A188CC
regular6=E4F1FF
regular7=C9C7C2
bright0=7E7D82
bright1=D05837
bright2=7E8D80
bright3=C4AE62
bright4=7E99B4
bright5=A188CC
bright6=E4F1FF
bright7=EEEDEA
