# dune-fremen - the desert hides its life
[cursor]
color=1B1710 E6D5A9

[colors]
background=1B1710
foreground=E6D5A9
selection-background=362E20
selection-foreground=E6D5A9
urls=C9D2D4
regular0=272117
regular1=CC6341
regular2=98A967
regular3=D2A855
regular4=5D9BC8
regular5=A188CC
regular6=C9D2D4
regular7=C6B287
bright0=928463
bright1=CC6341
bright2=98A967
bright3=D2A855
bright4=5D9BC8
bright5=A188CC
bright6=C9D2D4
bright7=E6D5A9
