# dune-tleilaxu - there is no fifth theme
[cursor]
color=131813 CDD5C2

[colors]
background=131813
foreground=CDD5C2
selection-background=283128
selection-foreground=CDD5C2
urls=85B7AE
regular0=1C241C
regular1=CC6055
regular2=7EA770
regular3=BDB47B
regular4=98BDB8
regular5=A188CC
regular6=85B7AE
regular7=A7B09B
bright0=788574
bright1=CC6055
bright2=7EA770
bright3=BDB47B
bright4=98BDB8
bright5=A188CC
bright6=85B7AE
bright7=CDD5C2
