# dune-corrino - the golden lion throne
[cursor]
color=1D1318 EFB63B

[colors]
background=1D1318
foreground=F2E2B8
selection-background=5A4526
selection-foreground=F2E2B8
urls=87A0AD
regular0=2A1C22
regular1=CE5B6B
regular2=99A75E
regular3=D4A63F
regular4=7290D9
regular5=A188CC
regular6=87A0AD
regular7=CFBC96
bright0=9A8781
bright1=CE5B6B
bright2=99A75E
bright3=D4A63F
bright4=7290D9
bright5=A188CC
bright6=87A0AD
bright7=F2E2B8
