# dune-atreides - the shoreline of two worlds
[cursor]
color=141B2A EAD9B4

[colors]
background=141B2A
foreground=EAD9B4
selection-background=2C3B4D
selection-foreground=EAD9B4
urls=8AC6BF
regular0=1E2938
regular1=CB6854
regular2=7FA871
regular3=DDB05E
regular4=649CD6
regular5=A188CC
regular6=8AC6BF
regular7=C9B58B
bright0=7C8899
bright1=CB6854
bright2=7FA871
bright3=DDB05E
bright4=649CD6
bright5=A188CC
bright6=8AC6BF
bright7=EAD9B4
