# dune-tleilaxu - there is no fifth theme
# add to tmux.conf: source-file ~/.config/tmux/dune-tleilaxu.conf

set -g status-style "bg=#1C241C,fg=#A7B09B"
set -g status-left-style "fg=#98BDB8,bold"
set -g status-right-style "fg=#A7B09B"
setw -g window-status-style "fg=#788574"
setw -g window-status-current-style "bg=#283128,fg=#CDD5C2,bold"
setw -g window-status-activity-style "fg=#BDB47B"
setw -g window-status-bell-style "fg=#CC6055"

set -g pane-border-style "fg=#283128"
set -g pane-active-border-style "fg=#98BDB8"

set -g message-style "bg=#1C241C,fg=#CDD5C2"
set -g message-command-style "bg=#1C241C,fg=#CDD5C2"
set -g mode-style "bg=#283128,fg=#CDD5C2"
set -g copy-mode-match-style "bg=#283128,fg=#CDD5C2"
set -g copy-mode-current-match-style "bg=#BDB47B,fg=#131813"

set -g display-panes-colour "#788574"
set -g display-panes-active-colour "#98BDB8"
setw -g clock-mode-colour "#98BDB8"
