# dune-harkonnen - the black sun (hard monochrome)
background #111113
foreground #EEEDEA
cursor #EEEDEA
cursor_text_color #111113
selection_background #29292E
selection_foreground #EEEDEA
url_color #E4F1FF
active_border_color #7E99B4
inactive_border_color #29292E
active_tab_background #29292E
active_tab_foreground #EEEDEA
inactive_tab_background #0A0A0B
inactive_tab_foreground #C9C7C2
color0 #1B1B1E
color1 #D05837
color2 #7E8D80
color3 #C4AE62
color4 #7E99B4
color5 #A188CC
color6 #E4F1FF
color7 #C9C7C2
color8 #7E7D82
color9 #D05837
color10 #7E8D80
color11 #C4AE62
color12 #7E99B4
color13 #A188CC
color14 #E4F1FF
color15 #EEEDEA
