# dune-fremen - the desert hides its life
background #1B1710
foreground #E6D5A9
cursor #E6D5A9
cursor_text_color #1B1710
selection_background #362E20
selection_foreground #E6D5A9
url_color #C9D2D4
active_border_color #5D9BC8
inactive_border_color #362E20
active_tab_background #362E20
active_tab_foreground #E6D5A9
inactive_tab_background #151109
inactive_tab_foreground #C6B287
color0 #272117
color1 #CC6341
color2 #98A967
color3 #D2A855
color4 #5D9BC8
color5 #A188CC
color6 #C9D2D4
color7 #C6B287
color8 #928463
color9 #CC6341
color10 #98A967
color11 #D2A855
color12 #5D9BC8
color13 #A188CC
color14 #C9D2D4
color15 #E6D5A9
