# dune-atreides - the shoreline of two worlds
background #141B2A
foreground #EAD9B4
cursor #EAD9B4
cursor_text_color #141B2A
selection_background #2C3B4D
selection_foreground #EAD9B4
url_color #8AC6BF
active_border_color #649CD6
inactive_border_color #2C3B4D
active_tab_background #2C3B4D
active_tab_foreground #EAD9B4
inactive_tab_background #0D121D
inactive_tab_foreground #C9B58B
color0 #1E2938
color1 #CB6854
color2 #7FA871
color3 #DDB05E
color4 #649CD6
color5 #A188CC
color6 #8AC6BF
color7 #C9B58B
color8 #7C8899
color9 #CB6854
color10 #7FA871
color11 #DDB05E
color12 #649CD6
color13 #A188CC
color14 #8AC6BF
color15 #EAD9B4
